# orm/_loading_cy.py
# Copyright (C) 2005-2026 the SQLAlchemy authors and contributors
# <see AUTHORS file>
#
# This module is part of SQLAlchemy and is released under
# the MIT License: https://www.opensource.org/licenses/mit-license.php
# mypy: disable-error-code="misc, type-arg, no-any-return"
from __future__ import annotations

from typing import Any
from typing import List
from typing import Optional
from weakref import ref

# START GENERATED CYTHON IMPORT
# This section is automatically generated by the script tools/cython_imports.py
try:
    # NOTE: the cython compiler needs this "import cython" in the file, it
    # can't be only "from sqlalchemy.util import cython" with the fallback
    # in that module
    import cython
except ModuleNotFoundError:
    from sqlalchemy.util import cython


def _is_compiled() -> bool:
    """Utility function to indicate if this module is compiled or not."""
    return cython.compiled  # type: ignore[no-any-return,unused-ignore]


# END GENERATED CYTHON IMPORT


@cython.cclass
class _InstancesBatch:
    """Batch row processor for the common "new instance" load path.

    Constructed by ``loading._instance_processor()``, this mirrors the
    per-row logic of its ``_instance()`` closure for rows that produce new
    instances, with all per-query constant conditions hoisted out of the
    row loop.  Rows for instances already present in the identity map
    delegate to ``_instance()`` itself, which handles refresh / partial
    population paths.

    """

    __slots__ = (
        "instance_proc",
        "identity_class",
        "identity_token",
        "primary_key_getter",
        "is_not_primary_key",
        "identity_map",
        "idmap_dict",
        "idmap_wr",
        "manager",
        "class_",
        "state_cls",
        "inline_state",
        "session_id",
        "runid",
        "set_load_opts",
        "loader_options",
        "load_path",
        "populate_existing",
        "pop_quick",
        "pop_quick_idx",
        "pk_idx",
        "pop_expire",
        "pop_new",
        "load_evt",
        "persistent_evt",
        "dispatch_load",
        "loaded_as_persistent",
        "context",
        "session",
        "post_load_states",
        "warn_for_runid_changed",
    )

    if cython.compiled:
        instance_proc: object = cython.declare(object)
        identity_class: object = cython.declare(object)
        identity_token: object = cython.declare(object)
        primary_key_getter: object = cython.declare(object)
        is_not_primary_key: object = cython.declare(object)
        identity_map: object = cython.declare(object)
        idmap_dict: dict = cython.declare(dict)
        idmap_wr: object = cython.declare(object)
        manager: object = cython.declare(object)
        class_: object = cython.declare(object)
        state_cls: object = cython.declare(object)
        inline_state: bool = cython.declare(cython.bint)
        session_id: object = cython.declare(object)
        runid: object = cython.declare(object)
        set_load_opts: bool = cython.declare(cython.bint)
        loader_options: object = cython.declare(object)
        load_path: object = cython.declare(object)
        populate_existing: bool = cython.declare(cython.bint)
        pop_quick: list = cython.declare(list)
        pop_quick_idx: object = cython.declare(object)
        pk_idx: int = cython.declare(cython.Py_ssize_t)
        pop_expire: list = cython.declare(list)
        pop_new: list = cython.declare(list)
        load_evt: bool = cython.declare(cython.bint)
        persistent_evt: bool = cython.declare(cython.bint)
        dispatch_load: object = cython.declare(object)
        loaded_as_persistent: object = cython.declare(object)
        context: object = cython.declare(object)
        session: object = cython.declare(object)
        post_load_states: object = cython.declare(object)
        warn_for_runid_changed: object = cython.declare(object)

    def __init__(
        self,
        instance_proc: Any,
        identity_class: Any,
        identity_token: Any,
        primary_key_getter: Any,
        is_not_primary_key: Any,
        identity_map: Any,
        manager: Any,
        state_cls: Optional[type],
        session_id: Any,
        runid: Any,
        set_load_opts: bool,
        loader_options: Any,
        load_path: Any,
        populate_existing: bool,
        pop_quick: List[Any],
        pop_expire: List[Any],
        pop_new: List[Any],
        load_evt: bool,
        persistent_evt: bool,
        loaded_as_persistent: Any,
        context: Any,
        post_load: Any,
        warn_for_runid_changed: Any,
    ) -> None:
        self.instance_proc = instance_proc
        self.identity_class = identity_class
        self.identity_token = identity_token
        self.primary_key_getter = primary_key_getter
        self.is_not_primary_key = is_not_primary_key
        self.identity_map = identity_map
        self.idmap_dict = identity_map._dict
        self.idmap_wr = identity_map._wr
        self.manager = manager
        self.class_ = manager.class_
        self.state_cls = state_cls
        self.inline_state = state_cls is not None
        self.session_id = session_id
        self.runid = runid
        self.set_load_opts = set_load_opts
        self.loader_options = loader_options
        self.load_path = load_path
        self.populate_existing = populate_existing
        self.pop_quick = pop_quick
        self.pop_expire = pop_expire
        self.pop_new = pop_new
        self.load_evt = load_evt
        self.persistent_evt = persistent_evt
        self.dispatch_load = manager.dispatch.load if load_evt else None
        self.loaded_as_persistent = loaded_as_persistent
        self.context = context
        self.session = context.session
        self.post_load_states = post_load.states if post_load else None
        self.warn_for_runid_changed = warn_for_runid_changed

        # probe single-index getters for their column positions so that
        # the row loop can index tuple rows directly; itemgetter resolves
        # an integer index against a range as a plain O(1) lookup
        probe = range(1 << 30)
        try:
            pk_probe = primary_key_getter(probe)
        except Exception:
            pk_probe = None
        if type(pk_probe) is range and len(pk_probe) == 1:
            self.pk_idx = pk_probe[0]
        else:
            self.pk_idx = -1

        quick_idx: Optional[List[Any]] = []
        for key, getter in pop_quick:
            try:
                idx = getter(probe)
            except Exception:
                quick_idx = None
                break
            if type(idx) is int:
                quick_idx.append((key, idx))
            else:
                quick_idx = None
                break
        self.pop_quick_idx = quick_idx

    def __call__(self, fetch: List[Any]) -> List[Any]:
        out: List[Any] = []

        instance_proc = self.instance_proc

        if "_add_unpresent" in self.identity_map.__dict__:
            # the identity map has been "killed" by Session.close() /
            # expunge_all(); delegate all rows to _instance(), which calls
            # the killed _add_unpresent and raises informatively
            return [instance_proc(row) for row in fetch]
        identity_class = self.identity_class
        identity_token = self.identity_token
        primary_key_getter = self.primary_key_getter
        is_not_primary_key = self.is_not_primary_key
        idmap_dict = self.idmap_dict
        idmap_wr = self.idmap_wr
        manager = self.manager
        class_ = self.class_
        state_cls = self.state_cls
        inline_state: cython.bint = self.inline_state
        session_id = self.session_id
        runid = self.runid
        set_load_opts: cython.bint = self.set_load_opts
        populate_existing: cython.bint = self.populate_existing
        pop_quick = self.pop_quick
        pop_expire = self.pop_expire
        pop_new = self.pop_new
        has_evts: cython.bint = self.load_evt or self.persistent_evt
        post_load_states = self.post_load_states

        # tuple rows allow direct indexed access for the primary key and
        # the quick (column value) populators
        pk_idx: cython.Py_ssize_t = self.pk_idx
        pop_quick_idx = self.pop_quick_idx
        i: cython.Py_ssize_t
        row_t: tuple
        use_idx: cython.bint = bool(
            pop_quick_idx is not None
            and pk_idx >= 0
            and fetch
            and type(fetch[0]) is tuple
        )

        for row in fetch:
            if use_idx:
                row_t = row
                pkval = row_t[pk_idx]
                if pkval is None:
                    # NULL primary key; no entity is returned for the row
                    out.append(None)
                    continue
                identitykey = (identity_class, (pkval,), identity_token)
                existing_state = idmap_dict.get(identitykey)
                if (
                    existing_state is not None
                    and existing_state.obj() is not None
                ):
                    out.append(instance_proc(row))
                    continue
            else:
                identitykey = (
                    identity_class,
                    primary_key_getter(row),
                    identity_token,
                )
                existing_state = idmap_dict.get(identitykey)
                if (
                    existing_state is not None
                    and existing_state.obj() is not None
                ):
                    # instance is already present in the identity map;
                    # delegate to _instance() which handles partial
                    # population, populate_existing, version checks etc.
                    out.append(instance_proc(row))
                    continue

                # check for non-NULL values in the primary key columns,
                # else no entity is returned for the row
                if is_not_primary_key(identitykey[1]):
                    out.append(None)
                    continue

            instance = class_.__new__(class_)
            if inline_state:
                # inlined equivalent of
                # manager._state_constructor(instance, manager) plus
                # manager._state_setter(instance, state), valid for the
                # default ClassManager / InstanceState combination.
                # committed_state / expired_attributes are slots with no
                # class-level default, so they must be initialized here
                # exactly as InstanceState.__init__ does.
                state = state_cls.__new__(state_cls)
                state.class_ = class_
                state.manager = manager
                state.committed_state = {}
                state.expired_attributes = set()
                state.obj = ref(instance, state._cleanup)
                instance._sa_instance_state = state
            else:
                state = manager._state_constructor(instance, manager)
                manager._state_setter(instance, state)
            dict_ = instance.__dict__

            state.key = identitykey
            state.identity_token = identity_token

            # attach instance to session
            state.session_id = session_id
            if has_evts:
                # event handlers can close the session mid-result; honor
                # a possibly-killed _add_unpresent on each row
                self.identity_map._add_unpresent(state, identitykey)
            else:
                # inlined form of
                # identity_map._add_unpresent(state, identitykey)
                idmap_dict[identitykey] = state
                state._instance_dict = idmap_wr

            if set_load_opts:
                state.load_options = self.loader_options
                state.load_path = self.load_path

            # full population for a new instance
            state.runid = runid

            if use_idx:
                row_t = row
                for pair in pop_quick_idx:
                    i = pair[1]
                    dict_[pair[0]] = row_t[i]
            else:
                for key, getter in pop_quick:
                    dict_[key] = getter(row)
            if populate_existing:
                for key, set_callable in pop_expire:
                    dict_.pop(key, None)
                    if set_callable:
                        state.expired_attributes.add(key)
            else:
                for key, set_callable in pop_expire:
                    if set_callable:
                        state.expired_attributes.add(key)

            for key, populator in pop_new:
                populator(state, dict_, row)

            if has_evts:
                existing_runid = state.runid
                if self.load_evt:
                    self.dispatch_load(state, self.context)
                    if state.runid != existing_runid:
                        self.warn_for_runid_changed(state)
                if self.persistent_evt:
                    self.loaded_as_persistent(self.session, state)
                    if state.runid != existing_runid:
                        self.warn_for_runid_changed(state)

            if populate_existing or state.modified:
                state._commit_all(dict_, self.context.session.identity_map)

            if post_load_states is not None:
                post_load_states[state] = True

            out.append(instance)

        return out
