"""this file is generated by tools/generate_sql_functions.py"""

from datetime import date
from datetime import datetime
from datetime import time
from decimal import Decimal
from typing import assert_type
from typing import Sequence

from sqlalchemy import column
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import Select
from sqlalchemy import select
from sqlalchemy import Sequence as SqlAlchemySequence
from sqlalchemy import String

# START GENERATED FUNCTION TYPING TESTS

# code within this block is **programmatically,
# statically generated** by tools/generate_sql_functions.py

stmt1 = select(func.abs(column("x", Integer)))

assert_type(stmt1, Select[int])


stmt2 = select(func.aggregate_strings(column("x", String), ","))

assert_type(stmt2, Select[str])


stmt3 = select(func.array_agg(column("x", Integer)))

assert_type(stmt3, Select[Sequence[int]])


stmt4 = select(func.avg())

assert_type(stmt4, Select[Decimal])


stmt5 = select(func.char_length(column("x")))

assert_type(stmt5, Select[int])


stmt6 = select(func.coalesce(column("x", Integer)))

assert_type(stmt6, Select[int])


stmt7 = select(func.concat())

assert_type(stmt7, Select[str])


stmt8 = select(func.count(column("x")))

assert_type(stmt8, Select[int])


stmt9 = select(func.cume_dist())

assert_type(stmt9, Select[Decimal])


stmt10 = select(func.current_date())

assert_type(stmt10, Select[date])


stmt11 = select(func.current_time())

assert_type(stmt11, Select[time])


stmt12 = select(func.current_timestamp())

assert_type(stmt12, Select[datetime])


stmt13 = select(func.current_user())

assert_type(stmt13, Select[str])


stmt14 = select(func.dense_rank())

assert_type(stmt14, Select[int])


stmt15 = select(func.localtime())

assert_type(stmt15, Select[datetime])


stmt16 = select(func.localtimestamp())

assert_type(stmt16, Select[datetime])


stmt17 = select(func.max(column("x", Integer)))

assert_type(stmt17, Select[int])


stmt18 = select(func.min(column("x", Integer)))

assert_type(stmt18, Select[int])


stmt19 = select(func.next_value(SqlAlchemySequence("x_seq")))

assert_type(stmt19, Select[int])


stmt20 = select(func.now())

assert_type(stmt20, Select[datetime])


stmt21 = select(func.percent_rank())

assert_type(stmt21, Select[Decimal])


stmt22 = select(func.pow(column("x", Integer)))

assert_type(stmt22, Select[int])


stmt23 = select(func.rank())

assert_type(stmt23, Select[int])


stmt24 = select(func.session_user())

assert_type(stmt24, Select[str])


stmt25 = select(func.sum(column("x", Integer)))

assert_type(stmt25, Select[int])


stmt26 = select(func.sysdate())

assert_type(stmt26, Select[datetime])


stmt27 = select(func.user())

assert_type(stmt27, Select[str])

# END GENERATED FUNCTION TYPING TESTS

stmt_count: Select[int, int, int] = select(
    func.count(), func.count("*"), func.count(1)
)
