"""Inspect and maintain ``test/profiles.txt``.

``test/profiles.txt`` stores the expected function call counts asserted by
the ``test/aaa_profiling/`` suite.  Every line is keyed to a "platform key"
that encodes the machine architecture, operating system, Python
implementation and version, the database / DBAPI in use, and whether or not
the C extensions were built.  A call count is only asserted when the running
environment matches a key that's present in the file; otherwise the test is
skipped.

The counts themselves are written by the test suite when it's run with
``--write-profiles`` / ``--force-write-profiles``; the ``profiles`` nox
session drives that across the full matrix of interpreters, backends and
cextension builds.

This module is the "everything else" part - what's in the file right now,
which backends a given part of the suite actually has counts for, and how to
get rid of entries that are no longer regenerated by anyone, such as those
for a Python version that's been dropped.

The file format itself, including the platform keys, is in
``lib/sqlalchemy/testing/profiles_file.py``, shared with the test suite side
that writes the counts out.

Run ``python tools/profiles.py --help`` for the command line.

"""

from __future__ import annotations

import argparse
import collections
import configparser
import fnmatch
import importlib.util
import os
from pathlib import Path
import re
import sys
from types import ModuleType
from typing import Dict
from typing import List
from typing import Optional
from typing import Sequence
from typing import Set
from typing import TYPE_CHECKING

HOME = Path(__file__).parent.parent


def _load_profiles_file_module() -> ModuleType:
    """Load ``sqlalchemy.testing.profiles_file`` straight from the tree.

    It's loaded by path rather than imported as part of the ``sqlalchemy``
    package so that this module, and the noxfile which imports it in the
    interpreter nox itself runs under, work without SQLAlchemy being
    installed; importing ``sqlalchemy.testing`` pulls in the whole library
    and its dependencies, whereas the module loaded here is standard
    library only.

    """

    path = HOME / "lib" / "sqlalchemy" / "testing" / "profiles_file.py"
    spec = importlib.util.spec_from_file_location(
        "sqlalchemy_testing_profiles_file", path
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


if TYPE_CHECKING:
    # for type checking only, the module is a normal member of the
    # sqlalchemy.testing package located by mypy_path
    from sqlalchemy.testing.profiles_file import PlatformKey
    from sqlalchemy.testing.profiles_file import ProfilesFile
    from sqlalchemy.testing.profiles_file import TestKey
else:
    _profiles_file = _load_profiles_file_module()

    PlatformKey = _profiles_file.PlatformKey
    ProfilesFile = _profiles_file.ProfilesFile
    TestKey = _profiles_file.TestKey

PROFILE_PYTHONS = ["3.13", "3.14"]
"""Python versions for which ``test/profiles.txt`` carries call counts.

This is the list of interpreters the ``profiles`` nox session will run, and
also what ``prune --stale`` considers current.   When a Python version is
added here, run the ``profiles`` session to seed its counts; when one is
removed, run ``python tools/profiles.py prune --stale`` to drop the entries
that are no longer being regenerated.

"""

PROFILE_DATABASES = ["sqlite", "postgresql", "mysql", "oracle", "mssql"]
"""``--db`` names the ``profiles`` nox session knows how to run against."""

_TEST_KEY_TOKEN = re.compile(r"^[\w.]+$")


def profile_file_path() -> Path:
    """Locate ``test/profiles.txt`` the same way the test suite does."""

    config = configparser.ConfigParser()
    config.read(HOME / "setup.cfg")
    return HOME / config.get("sqla_testing", "profile_file")


def test_keys_for_selection(
    profiles: ProfilesFile, selection: Optional[Sequence[str]]
) -> Optional[Set[TestKey]]:
    """Return the test keys matched by a pytest-style selection.

    Returns ``None`` if the selection can't be interpreted, meaning
    "assume everything".

    """

    prefixes = _selection_to_prefixes(selection)
    if prefixes is None:
        return None

    return {
        test_key
        for test_key in profiles.test_keys()
        if any(_key_matches(test_key, prefix) for prefix in prefixes)
    }


def databases_for_selection(
    profiles: ProfilesFile, selection: Optional[Sequence[str]]
) -> Set[str]:
    """Return the ``--db`` names that have call counts recorded for a
    pytest-style selection.

    A selection that matches nothing at all in the file, such as a newly
    written test, yields all databases; there's no way to know from here
    which backends the new tests will actually run on, and backends the
    tests skip on simply won't record anything.

    """

    test_keys = test_keys_for_selection(profiles, selection)
    if test_keys is None:
        return set(PROFILE_DATABASES)

    databases = {
        platform_key.database
        for test_key in test_keys
        for platform_key in profiles.platforms_for(test_key)
    } & set(PROFILE_DATABASES)

    return databases or set(PROFILE_DATABASES)


def recorded_databases(selection: Optional[Sequence[str]]) -> Set[str]:
    """``databases_for_selection()`` against the default profile file.

    This is the entrypoint used by the ``profiles`` nox session.

    """

    return databases_for_selection(
        ProfilesFile(profile_file_path()), selection
    )


def _key_matches(test_key: TestKey, prefix: str) -> bool:
    return (
        test_key == prefix
        or test_key.startswith(prefix + ".")
        or test_key.startswith(prefix + "[")
    )


def _selection_to_prefixes(
    selection: Optional[Sequence[str]],
) -> Optional[List[str]]:
    """Translate pytest file / node id arguments into test key prefixes.

    ``test/aaa_profiling/test_orm.py::MergeTest`` becomes
    ``test.aaa_profiling.test_orm.MergeTest``.  Anything that isn't a plain
    path or node id - ``-k`` expressions, ``-m`` markers, etc. - makes the
    whole selection uninterpretable and returns ``None``.

    """

    if not selection:
        return None

    prefixes = []
    for arg in selection:
        if arg.startswith("-"):
            return None

        path, _, node_id = arg.partition("::")
        path = path.replace(os.sep, "/").rstrip("/")
        if path.endswith(".py"):
            path = path[:-3]

        dotted = path.replace("/", ".")
        if node_id:
            dotted = f"{dotted}.{node_id.replace('::', '.')}"

        if not _TEST_KEY_TOKEN.match(dotted.split("[")[0]):
            return None

        prefixes.append(dotted)

    return prefixes


def _orphan_test_keys(profiles: ProfilesFile) -> Set[TestKey]:
    """Return test keys whose module / class / method no longer exist.

    This is a deliberately coarse source scan rather than a pytest
    collection: a key is an orphan only if its module file is gone, or the
    module's source contains neither the class name nor the method name.
    It catches deleted and renamed tests without needing a working test
    environment, and won't flag a test just because it can't run here.

    """

    orphans: Set[TestKey] = set()
    sources: Dict[str, Optional[str]] = {}

    for test_key in profiles.test_keys():
        module_name, class_name, test_name = test_key.rsplit(".", 2)
        test_name = test_name.split("[")[0]

        if module_name not in sources:
            path = HOME / (module_name.replace(".", "/") + ".py")
            sources[module_name] = path.read_text() if path.exists() else None

        source = sources[module_name]
        if source is None:
            orphans.add(test_key)
        elif not re.search(
            rf"^class {re.escape(class_name)}\b", source, re.MULTILINE
        ):
            orphans.add(test_key)
        elif not re.search(rf"\bdef {re.escape(test_name)}\s*\(", source):
            orphans.add(test_key)

    return orphans


def _stale_platform_keys(profiles: ProfilesFile) -> List[PlatformKey]:
    return sorted(
        (
            key
            for key in profiles.platform_keys()
            if key.python not in PROFILE_PYTHONS
        ),
        key=str,
    )


def _cmd_show(profiles: ProfilesFile, options: argparse.Namespace) -> int:
    keys = sorted(profiles.platform_keys(), key=str)

    per_key: Dict[PlatformKey, int] = collections.Counter()
    for test_key in profiles.test_keys():
        for platform_key in profiles.platforms_for(test_key):
            per_key[platform_key] += 1

    print(
        f"{profiles.path}: {len(profiles.test_keys())} tests, "
        f"{len(keys)} platforms, "
        f"{profiles.entry_count()} entries"
    )

    print()
    print(
        f"{'python':<8} {'dialect':<12} {'driver':<12} {'cext':<12} "
        f"{'tests':>6}"
    )
    print("-" * 54)
    for key in keys:
        print(
            f"{key.python:<8} {key.dialect:<12} "
            f"{key.driver:<12} {key.cext_token:<12} "
            f"{per_key[key]:>6}"
        )

    print()
    for name, values in (
        ("machines", {key.machine for key in keys}),
        ("systems", {key.system for key in keys}),
        ("implementations", {key.implementation for key in keys}),
        ("pythons", {key.python for key in keys}),
        ("databases", {key.database for key in keys}),
    ):
        print(f"{name:<18} {', '.join(sorted(values))}")

    if options.tests:
        print()
        by_databases: Dict[str, List[str]] = collections.defaultdict(list)
        for test_key in profiles.test_keys():
            names = sorted(
                {key.database for key in profiles.platforms_for(test_key)}
            )
            by_databases[", ".join(names)].append(test_key)
        for db_names, test_keys in sorted(by_databases.items()):
            print(f"{len(test_keys)} tests recorded for: {db_names}")
            for test_key in sorted(test_keys):
                print(f"    {test_key}")

    return 0


def _cmd_check(profiles: ProfilesFile, options: argparse.Namespace) -> int:
    stale = _stale_platform_keys(profiles)
    orphans = sorted(_orphan_test_keys(profiles))

    for key in stale:
        print(f"stale platform (python not in PROFILE_PYTHONS): {key}")
    for test_key in orphans:
        print(f"orphan test (no matching source): {test_key}")

    if stale or orphans:
        print()
        print(
            "run 'python tools/profiles.py prune --stale --orphans' "
            "to remove these"
        )
        return 1

    print("test/profiles.txt is up to date")
    return 0


def _cmd_prune(profiles: ProfilesFile, options: argparse.Namespace) -> int:
    drop_platform: List[str] = list(options.platform)
    if options.stale:
        drop_platform.extend(
            str(key) for key in _stale_platform_keys(profiles)
        )
    for python in options.python:
        drop_platform.append(f"*_{python}_*")
    for database in options.database:
        drop_platform.extend(
            str(key)
            for key in profiles.platform_keys()
            if key.database == database
        )

    drop_test = set(options.test)
    if options.orphans:
        drop_test.update(_orphan_test_keys(profiles))

    if not any(
        (
            options.stale,
            options.orphans,
            options.python,
            options.database,
            options.platform,
            options.test,
        )
    ):
        print(
            "nothing selected; pass --stale, --orphans, --python, "
            "--database, --platform or --test"
        )
        return 1

    removed = 0
    for test_key in list(profiles.test_keys()):
        if any(_key_matches(test_key, prefix) for prefix in drop_test):
            dropped = profiles.remove_test(test_key)
            removed += dropped
            print(f"removing all {dropped} entries for {test_key}")
            continue

        for platform_key in list(profiles.platforms_for(test_key)):
            if any(
                fnmatch.fnmatch(str(platform_key), pattern)
                for pattern in drop_platform
            ):
                removed += 1
                profiles.remove_entry(test_key, platform_key)
                if options.verbose:
                    print(f"removing {test_key} {platform_key}")

    if options.dry_run:
        print(f"would remove {removed} entries (dry run, nothing written)")
    else:
        profiles.write()
        print(f"removed {removed} entries from {profiles.path}")

    return 0


def _cmd_databases(profiles: ProfilesFile, options: argparse.Namespace) -> int:
    for database in sorted(
        databases_for_selection(profiles, options.selection)
    ):
        print(database)
    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--file",
        type=Path,
        default=None,
        help="path to profiles.txt (default: from setup.cfg)",
    )
    subparsers = parser.add_subparsers(dest="command")

    show = subparsers.add_parser(
        "show", help="summarize what's recorded in the file"
    )
    show.add_argument(
        "--tests",
        action="store_true",
        help="also list each test grouped by the databases it's recorded for",
    )
    show.set_defaults(fn=_cmd_show)

    check = subparsers.add_parser(
        "check",
        help="exit nonzero if the file has stale or orphaned entries",
    )
    check.set_defaults(fn=_cmd_check)

    prune = subparsers.add_parser(
        "prune", help="remove entries that are no longer regenerated"
    )
    prune.add_argument(
        "--stale",
        action="store_true",
        help="remove entries for Python versions not in PROFILE_PYTHONS",
    )
    prune.add_argument(
        "--orphans",
        action="store_true",
        help="remove entries for tests that no longer exist in the source",
    )
    prune.add_argument(
        "--python",
        action="append",
        default=[],
        metavar="VERSION",
        help="remove entries for this Python version, e.g. 3.12",
    )
    prune.add_argument(
        "--database",
        action="append",
        default=[],
        metavar="DB",
        help="remove entries for this --db name, e.g. mssql",
    )
    prune.add_argument(
        "--platform",
        action="append",
        default=[],
        metavar="GLOB",
        help="remove entries whose platform key matches this glob, "
        "e.g. '*_darwin_*'",
    )
    prune.add_argument(
        "--test",
        action="append",
        default=[],
        metavar="TESTKEY",
        help="remove all entries for this test key or dotted prefix",
    )
    prune.add_argument(
        "-n", "--dry-run", action="store_true", help="don't write the file"
    )
    prune.add_argument(
        "-v", "--verbose", action="store_true", help="log every entry removed"
    )
    prune.set_defaults(fn=_cmd_prune)

    databases = subparsers.add_parser(
        "databases",
        help="print the --db names that have call counts for a pytest "
        "selection",
    )
    databases.add_argument("selection", nargs="*")
    databases.set_defaults(fn=_cmd_databases)

    options = parser.parse_args(argv)
    if options.command is None:
        parser.print_help()
        return 1

    path = options.file if options.file is not None else profile_file_path()
    return int(options.fn(ProfilesFile(path), options))


if __name__ == "__main__":
    sys.exit(main())
